name: Build APK

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build the APK
        run: |
          cd clients/android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload the APK
        uses: actions/upload-artifact@v2
        with:
          name: mauth
          path: clients/android/app/build/outputs/apk/debug/app-debug.apk