name: Build APK

on:
  push:
    branches:
      - '*'
    paths: ["clients/android/**"]
    
  pull_request:
    branches:
      - '*'
    paths: ["clients/android/**"]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build the APK
        run: |
          cd clients/android
          chmod +x gradlew
          ./gradlew assembleRelease
          
      - uses: r0adkll/sign-android-release@v1
        name: Sign the APK
        id: signing
        with:
          releaseDirectory: clients/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYHASH }}
          alias: ${{ secrets.KEYALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload the APK
        uses: actions/upload-artifact@v2
        with:
          name: uwuradio
          path: ${{steps.signing.outputs.signedReleaseFile}}
